#!/bin/bash

cd "$(dirname "$0")"
source "./lswrapper-util.sh"

ls_lang="python"
ls_exec_cmd=("./bin/pyls")

ls_init() {
    pip3 install --install-option="--prefix=$PWD" --ignore-installed "python-language-server[all]"
}

ls_require_command python3
ls_require_command pip3

export PYTHONPATH="$PYTHONPATH:$(echo "$(ls_data_path)"/lib/python3.*)"/site-packages
ls_main
