#!/bin/bash

cd "$(dirname "$0")"
source "./lswrapper-util.sh"

ls_lang="scala"
ls_exec_cmd=("./metals-vim")

ls_init() {
    tmpdir="$(mktemp -d)"
    ls_download "$tmpdir" "https://git.io/coursier"
    chmod +x "$tmpdir/coursier"

    "$tmpdir/coursier" bootstrap \
        --java-opt -Xss4m \
        --java-opt -Xms100m \
        --java-opt -Dmetals.client=coc.nvim \
        org.scalameta:metals_2.12:0.7.0 \
        -r bintray:scalacenter/releases \
        -r sonatype:snapshots \
        -o ./metals-vim -f
}

ls_require_command java
ls_main
